let

//Get a list of OwnerHistory for a given revisionId and projectId
GetOwnerHistory = (projectId as text, revisionId as text,token as text) as list =>
let 
	ownerHistories = RESTFunctionWithoutPage("/v2/projects/" & projectId & "/ifc/ownerhistory",revisionId,token),
	ownerHistoriesWithProjectId = List.Transform(ownerHistories, each Record.AddField(_,"projectId",projectId)),
	ownerHistoriesWithRevisionId = List.Transform(ownerHistoriesWithProjectId, each Record.AddField(_,"revisionGUID",revisionId))
in
	ownerHistoriesWithRevisionId,

//The main function starts here
token = GetToken(),
revisionList = List.Combine(List.Transform(projectsList(token), each revisionsList(_[id],token))),
ownerHistories = List.Combine(List.Transform(revisionList, each GetOwnerHistory(_[projectId],_[id],token))),

ownerHistoriesWithTheOrganizationName = List.Transform(ownerHistories, each Record.AddField(_,"attributes.OwningUser.TheOrganization.Name",_[attributes][OwningUser][value][attributes][TheOrganization][value][attributes][Name][value])),
ownerHistoriesWithTheOrganizationDescription = List.Transform(ownerHistoriesWithTheOrganizationName, each Record.AddField(_,"attributes.OwningUser.TheOrganization.Description",_[attributes][OwningUser][value][attributes][TheOrganization][value][attributes][Description][value])),
ownerHistoriesWithTheOrganizationAddresses = List.Transform(ownerHistoriesWithTheOrganizationDescription, each Record.AddField(_,"attributes.OwningUser.TheOrganization.Addresses",List.First(_[attributes][OwningUser][value][attributes][TheOrganization][value][attributes][Addresses][value],[value = null])[value])),
ownerHistoriesWithTheOrganizationId = List.Transform(ownerHistoriesWithTheOrganizationAddresses, each Record.AddField(_,"attributes.OwningUser.TheOrganization.Id",_[attributes][OwningUser][value][attributes][TheOrganization][value][attributes][Id][value])),
ownerHistoriesWithTheOrganizationRoles = List.Transform(ownerHistoriesWithTheOrganizationId, each Record.AddField(_,"attributes.OwningUser.TheOrganization.Roles",List.First(_[attributes][OwningUser][value][attributes][TheOrganization][value][attributes][Roles][value],[value = null])[value])),
ownerHistoriesWithThePersonAddresses = List.Transform(ownerHistoriesWithTheOrganizationRoles, each Record.AddField(_,"attributes.OwningUser.ThePerson.Addresses",List.First(_[attributes][OwningUser][value][attributes][ThePerson][value][attributes][Addresses][value],[value = null])[value])),
ownerHistoriesWithThePersonSuffixTitles = List.Transform(ownerHistoriesWithThePersonAddresses, each Record.AddField(_,"attributes.OwningUser.ThePerson.SuffixTitles",List.First(_[attributes][OwningUser][value][attributes][ThePerson][value][attributes][SuffixTitles][value],[value = null])[value])),
ownerHistoriesWithThePersonPrefixTitles = List.Transform(ownerHistoriesWithThePersonSuffixTitles, each Record.AddField(_,"attributes.OwningUser.ThePerson.PrefixTitles",List.First(_[attributes][OwningUser][value][attributes][ThePerson][value][attributes][PrefixTitles][value],[value = null])[value])),
ownerHistoriesWithThePersonGivenName = List.Transform(ownerHistoriesWithThePersonPrefixTitles, each Record.AddField(_,"attributes.OwningUser.ThePerson.GivenName",_[attributes][OwningUser][value][attributes][ThePerson][value][attributes][GivenName][value])),
ownerHistoriesWithThePersonMiddleNames = List.Transform(ownerHistoriesWithThePersonGivenName, each Record.AddField(_,"attributes.OwningUser.ThePerson.MiddleNames",List.First(_[attributes][OwningUser][value][attributes][ThePerson][value][attributes][MiddleNames][value],[value = null])[value])),
ownerHistoriesWithThePersonId = List.Transform(ownerHistoriesWithThePersonMiddleNames, each Record.AddField(_,"attributes.OwningUser.ThePerson.Id",_[attributes][OwningUser][value][attributes][ThePerson][value][attributes][Id][value])),
ownerHistoriesWithThePersonFamilyName = List.Transform(ownerHistoriesWithThePersonId, each Record.AddField(_,"attributes.OwningUser.ThePerson.FamilyName",_[attributes][OwningUser][value][attributes][ThePerson][value][attributes][FamilyName][value])),
ownerHistoriesWithThePersonRoles = List.Transform(ownerHistoriesWithThePersonFamilyName, each Record.AddField(_,"attributes.OwningUser.ThePerson.Roles",List.First(_[attributes][OwningUser][value][attributes][ThePerson][value][attributes][Roles][value],[value = null])[value])),
ownerHistoriesWithApplicationDeveloperName = List.Transform(ownerHistoriesWithThePersonRoles, each Record.AddField(_,"attributes.OwningApplication.ApplicationDeveloper.Name",_[attributes][OwningApplication][value][attributes][ApplicationDeveloper][value][attributes][Name][value])),
ownerHistoriesWithApplicationDeveloperDescription = List.Transform(ownerHistoriesWithApplicationDeveloperName, each Record.AddField(_,"attributes.OwningApplication.ApplicationDeveloper.Description",_[attributes][OwningApplication][value][attributes][ApplicationDeveloper][value][attributes][Description][value])),
ownerHistoriesWithApplicationDeveloperAddresses = List.Transform(ownerHistoriesWithApplicationDeveloperDescription, each Record.AddField(_,"attributes.OwningApplication.ApplicationDeveloper.Addresses",List.First(_[attributes][OwningApplication][value][attributes][ApplicationDeveloper][value][attributes][Addresses][value],[value = null])[value])),
ownerHistoriesWithApplicationDeveloperId = List.Transform(ownerHistoriesWithApplicationDeveloperAddresses, each Record.AddField(_,"attributes.OwningApplication.ApplicationDeveloper.Id",_[attributes][OwningApplication][value][attributes][ApplicationDeveloper][value][attributes][Id][value])),
ownerHistoriesWithApplicationDeveloperRoles = List.Transform(ownerHistoriesWithApplicationDeveloperId, each Record.AddField(_,"attributes.OwningApplication.ApplicationDeveloper.Roles",List.First(_[attributes][OwningApplication][value][attributes][ApplicationDeveloper][value][attributes][Roles][value],[value = null])[value])),

ownerHistoriesWithApplicationFullName = List.Transform(ownerHistoriesWithApplicationDeveloperRoles, each Record.AddField(_,"attributes.OwningApplication.ApplicationFullName",_[attributes][OwningApplication][value][attributes][ApplicationFullName][value])),
ownerHistoriesWithVersion = List.Transform(ownerHistoriesWithApplicationFullName, each Record.AddField(_,"attributes.OwningApplication.Version",_[attributes][OwningApplication][value][attributes][Version][value])),
ownerHistoriesWithApplicationIdentifier = List.Transform(ownerHistoriesWithVersion, each Record.AddField(_,"attributes.OwningApplication.ApplicationIdentifier",_[attributes][OwningApplication][value][attributes][ApplicationIdentifier][value])),

ownerHistoriesWithLastModifiedDate = List.Transform(ownerHistoriesWithApplicationIdentifier, each Record.AddField(_,"attributes.LastModifiedDate",#datetime(1970, 1, 1, 0, 0, 0) + #duration(0, 0, 0, _[attributes][LastModifiedDate][value]))),
ownerHistoriesWithCreationDate = List.Transform(ownerHistoriesWithLastModifiedDate, each Record.AddField(_,"attributes.CreationDate",#datetime(1970, 1, 1, 0, 0, 0) + #duration(0, 0, 0,_[attributes][CreationDate][value]))),

ownerHistoriesWithChangeAction = List.Transform(ownerHistoriesWithCreationDate, each Record.AddField(_,"attributes.ChangeAction",_[attributes][ChangeAction][value])),

ownerHistoriesInitialTable = Table.FromList(ownerHistoriesWithChangeAction, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
ownerHistoriesTable = Table.ExpandRecordColumn(ownerHistoriesInitialTable, "Column1", {"objectId", "ifcType", "attributes", "projectId", "revisionGUID", "attributes.OwningUser.TheOrganization.Name", "attributes.OwningUser.TheOrganization.Description", "attributes.OwningUser.TheOrganization.Addresses", "attributes.OwningUser.TheOrganization.Id", "attributes.OwningUser.TheOrganization.Roles", "attributes.OwningUser.ThePerson.Addresses", "attributes.OwningUser.ThePerson.SuffixTitles", "attributes.OwningUser.ThePerson.PrefixTitles", "attributes.OwningUser.ThePerson.GivenName", "attributes.OwningUser.ThePerson.MiddleNames", "attributes.OwningUser.ThePerson.Id", "attributes.OwningUser.ThePerson.FamilyName", "attributes.OwningUser.ThePerson.Roles", "attributes.OwningApplication.ApplicationDeveloper.Name", "attributes.OwningApplication.ApplicationDeveloper.Description", "attributes.OwningApplication.ApplicationDeveloper.Addresses", "attributes.OwningApplication.ApplicationDeveloper.Id", "attributes.OwningApplication.ApplicationDeveloper.Roles", "attributes.OwningApplication.ApplicationFullName", "attributes.OwningApplication.Version", "attributes.OwningApplication.ApplicationIdentifier", "attributes.LastModifiedDate", "attributes.CreationDate", "attributes.ChangeAction"}, {"objectId", "ifcType", "attributes", "projectId", "revisionId", "attributes.OwningUser.TheOrganization.Name", "attributes.OwningUser.TheOrganization.Description", "attributes.OwningUser.TheOrganization.Addresses", "attributes.OwningUser.TheOrganization.Id", "attributes.OwningUser.TheOrganization.Roles", "attributes.OwningUser.ThePerson.Addresses", "attributes.OwningUser.ThePerson.SuffixTitles", "attributes.OwningUser.ThePerson.PrefixTitles", "attributes.OwningUser.ThePerson.GivenName", "attributes.OwningUser.ThePerson.MiddleNames", "attributes.OwningUser.ThePerson.Id", "attributes.OwningUser.ThePerson.FamilyName", "attributes.OwningUser.ThePerson.Roles", "attributes.OwningApplication.ApplicationDeveloper.Name", "attributes.OwningApplication.ApplicationDeveloper.Description", "attributes.OwningApplication.ApplicationDeveloper.Addresses", "attributes.OwningApplication.ApplicationDeveloper.Id", "attributes.OwningApplication.ApplicationDeveloper.Roles", "attributes.OwningApplication.ApplicationFullName", "attributes.OwningApplication.Version", "attributes.OwningApplication.ApplicationIdentifier", "attributes.LastModifiedDate", "attributes.CreationDate", "attributes.ChangeAction"}),
    #"Changed Type" = Table.TransformColumnTypes(ownerHistoriesTable,{{"attributes.CreationDate", type datetime}, {"attributes.LastModifiedDate", type datetime}})
in
    #"Changed Type"